spring:
  application:
    name: events
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/events
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    livereload:
      port: 35730

server:
  port: 8081
  servlet:
    context-path: /events

