version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/

  tutorials:
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        APP: tutorials
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - ./:/app
      - ./apps/tutorials/.m2:/root.m2
    tty: true

  events:
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        APP: events
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    ports:
      - "8081:8081"
      - "35730:35730"
    volumes:
      - ./:/app
      - ./apps/events/.m2:/root/.m2
    tty: true

volumes:
  db:
