version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  order-service:
    build:
      context: ./
      dockerfile: Dockerfile.local
    env_file: ./.env
    depends_on:
      - db
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - ./:/app
      - .m2:/root/.m2
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://db:5432/$POSTGRES_DB",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD"
      }'
    tty: true

volumes:
  db: