spring:
  application:
    name: tutorials
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/tutorials
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  cloud:
    discovery:
      client:
        simple:
          instances:
            events:
              - uri: http://localhost:8081
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    feign: INFO
    com:
      superluminar:
        tutorials:
          client: INFO

server:
  servlet:
    context-path: /tutorials