spring:
  application:
    name: tutorials
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/tutorials
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  client:
    config:
      default:
        loggerLevel: full
logging:
  level:
    feign: INFO
    com:
      superluminar:
        tutorials:
          client: INFO
